image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1807.12121,    0.     ,  711.11997,
            0.     , 1806.46896,  562.49495,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.078049, 0.158627, 0.000304, -0.000566, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1790.52356,    0.     ,  710.04861,    0.     ,
            0.     , 1794.3208 ,  562.32704,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
